# Inspired from https://foojay.io/today/how-to-release-a-java-module-with-jreleaser-to-maven-central-with-github-actions/
name: Publish a new Maven Central release

on:
  workflow_call:
    inputs:
      publish-cmd:
        description: 'Command to perform publish'
        required: true
        type: string
      jdk-versions:
        description: 'JDK version(s) to install for module builds'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Java setup
        uses: actions/setup-java@v5
        with:
          java-version: ${{ inputs.jdk-versions }}
          distribution: 'temurin'
          cache: maven
      - name: Run a build of the code base before release
        run: ./mvnw --batch-mode --no-transfer-progress clean install
      # - name: Set release version
      #   run: ./mvnw --batch-mode --no-transfer-progress versions:set -DnewVersion=${{ github.event.inputs.version }}
      - name: Release with JReleaser
        env:
          JRELEASER_TAG_NAME: ${{ github.event.inputs.version }}
          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.MAVEN_CENTRAL_GPG_PUBLIC_KEY }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.MAVEN_CENTRAL_GPG_SECRET_KEY }}
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.MAVEN_CENTRAL_GPG_PASSPHRASE }}
          JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_NEXUS2_USERNAME }}
          JRELEASER_MAVENCENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_NEXUS2_PASSWORD }}
          JRELEASER_NEXUS2_USERNAME: ${{ secrets.MAVEN_CENTRAL_NEXUS2_USERNAME }}
          JRELEASER_NEXUS2_PASSWORD: ${{ secrets.MAVEN_CENTRAL_NEXUS2_PASSWORD }}
          JRELEASER_GITHUB_TOKEN: ${{ secrets.SUBMODULE_TOKEN }}
        run: ${{ inputs.publish-cmd }}
